# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tools/liveupdate_ddf.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'tools/liveupdate_ddf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atools/liveupdate_ddf.proto\x12\x0f\x64mLiveUpdateDDF\"\x1a\n\nHashDigest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\"\xb2\x02\n\x0eManifestHeader\x12L\n\x17resource_hash_algorithm\x18\x01 \x02(\x0e\x32\x1e.dmLiveUpdateDDF.HashAlgorithm:\x0bHASH_SHA256\x12M\n\x18signature_hash_algorithm\x18\x02 \x02(\x0e\x32\x1e.dmLiveUpdateDDF.HashAlgorithm:\x0bHASH_SHA256\x12J\n\x18signature_sign_algorithm\x18\x03 \x02(\x0e\x32\x1e.dmLiveUpdateDDF.SignAlgorithm:\x08SIGN_RSA\x12\x37\n\x12project_identifier\x18\x04 \x02(\x0b\x32\x1b.dmLiveUpdateDDF.HashDigest\"\xa6\x01\n\rResourceEntry\x12)\n\x04hash\x18\x01 \x02(\x0b\x32\x1b.dmLiveUpdateDDF.HashDigest\x12\x0b\n\x03url\x18\x02 \x02(\t\x12\x10\n\x08url_hash\x18\x03 \x02(\x04\x12\x0c\n\x04size\x18\x04 \x02(\r\x12\x17\n\x0f\x63ompressed_size\x18\x05 \x02(\r\x12\x10\n\x05\x66lags\x18\x06 \x02(\r:\x01\x30\x12\x12\n\ndependants\x18\x07 \x03(\x04\"\xcf\x01\n\x0cManifestData\x12/\n\x06header\x18\x01 \x02(\x0b\x32\x1f.dmLiveUpdateDDF.ManifestHeader\x12\x34\n\x0f\x65ngine_versions\x18\x02 \x03(\x0b\x32\x1b.dmLiveUpdateDDF.HashDigest\x12\x31\n\tresources\x18\x03 \x03(\x0b\x32\x1e.dmLiveUpdateDDF.ResourceEntry\x12%\n\x16has_excluded_resources\x18\x04 \x01(\x08:\x05\x66\x61lse\"_\n\x0cManifestFile\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x12\x11\n\tsignature\x18\x02 \x02(\x0c\x12\x1a\n\x12\x61rchive_identifier\x18\x03 \x01(\x0c\x12\x12\n\x07version\x18\x04 \x02(\r:\x01\x30*`\n\rHashAlgorithm\x12\x10\n\x0cHASH_UNKNOWN\x10\x00\x12\x0c\n\x08HASH_MD5\x10\x01\x12\r\n\tHASH_SHA1\x10\x02\x12\x0f\n\x0bHASH_SHA256\x10\x03\x12\x0f\n\x0bHASH_SHA512\x10\x04*/\n\rSignAlgorithm\x12\x10\n\x0cSIGN_UNKNOWN\x10\x00\x12\x0c\n\x08SIGN_RSA\x10\x01*M\n\x11ResourceEntryFlag\x12\x0b\n\x07\x42UNDLED\x10\x01\x12\x0c\n\x08\x45XCLUDED\x10\x02\x12\r\n\tENCRYPTED\x10\x04\x12\x0e\n\nCOMPRESSED\x10\x08\x42\'\n\x1b\x63om.dynamo.liveupdate.protoB\x08Manifest')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tools.liveupdate_ddf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.dynamo.liveupdate.protoB\010Manifest'
  _globals['_HASHALGORITHM']._serialized_start=860
  _globals['_HASHALGORITHM']._serialized_end=956
  _globals['_SIGNALGORITHM']._serialized_start=958
  _globals['_SIGNALGORITHM']._serialized_end=1005
  _globals['_RESOURCEENTRYFLAG']._serialized_start=1007
  _globals['_RESOURCEENTRYFLAG']._serialized_end=1084
  _globals['_HASHDIGEST']._serialized_start=47
  _globals['_HASHDIGEST']._serialized_end=73
  _globals['_MANIFESTHEADER']._serialized_start=76
  _globals['_MANIFESTHEADER']._serialized_end=382
  _globals['_RESOURCEENTRY']._serialized_start=385
  _globals['_RESOURCEENTRY']._serialized_end=551
  _globals['_MANIFESTDATA']._serialized_start=554
  _globals['_MANIFESTDATA']._serialized_end=761
  _globals['_MANIFESTFILE']._serialized_start=763
  _globals['_MANIFESTFILE']._serialized_end=858
# @@protoc_insertion_point(module_scope)
